version: '3.8'

services:
  blog_cms_service:
    container_name: blog_cms_service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - blog_cms_service_mongodb
      - blog_cms_service_redis
    volumes:
      - ./uploads:/opt/app/uploads


  blog_cms_service_mongodb:
    image: mongo:latest
    container_name: blog_cms_service_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db

  blog_cms_service_redis:
    image: redis:latest
    container_name: blog_cms_service_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  mongo-data:
  redis-data:
