export const PAGE_ROUTE_HOMEPAGE = "/"
export const PAGE_ROUTE_FAQ = "/faq"
export const PAGE_ROUTE_PRIVACY_POLICY = "/privacy-policy"
export const PAGE_ROUTE_TERM = "/terms"
export const PAGE_ROUTE_CONTACT = "/contact"
export const PAGE_ROUTE_GOLD_INVEST_CALCULATOR = "/gia-lap-dau-tu-vang"
export const PAGE_ROUTE_GOLD_INVEST_PER_MONTH = "/gia-lap-dau-tu-hang-thang"
export const PAGE_ROUTE_CONVERT_SALARY_TO_GOLD = "/luong-sang-vang"
export const PAGE_ROUTE_CALCULATE_PRICE_TODAY = "/tinh-gia-vang-hom-nay"
export const PAGE_ROUTE_DEMO = "/dung-thu-tinh-nang"
export const PAGE_ROUTE_DISCLAIMER = "/mien-tru-trach-nhiem"
export const PAGE_ROUTE_WORLD_GOLD_PRICE = "/gia-vang-the-gioi"
export const PAGE_ROUTE_GOLD_PRICE_TODAY = "/gia-vang-hom-nay"

export const USER_PUBLIC_PAGE_ROUTE_SHOP = "/cua-hang"
export const PRIVATE_PAGE_ROUTE_INDIVIDUAL = "/ca-nhan"

export const AUTH_PAGE_ROUTE_LOGOUT = "/dang-xuat"
export const AUTH_PAGE_ROUTE_LOGIN = "/dang-nhap"
